version: '3.7'

services:
  mssql:
    image: microsoft/mssql-server-linux
    restart: always
    volumes:
      - mssql-volume:/var/opt/mssql
    env_file:
      - .env
    ports:
      - "14330:1433"

volumes:
  mssql-volume:
